name: PR preview

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      MPKIT_URL: ${{ secrets.MPKIT_PREVIEW_URL }}
      ASSET_PREFIX: ${{ vars.PREVIEW_ASSET_PREFIX }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install and run eslint
        id: eslint-ci
        run: npm install && npm run eslint:mdx:ci

      - name: PR comment with eslint error
        if: failure() && steps.eslint-ci.outcome != 'success'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: reports/eslint-mdx.txt

      - name: Install Docskit Dependencies
        run: |
          cd src
          npm install --legacy-peer-deps

      - name: Build
        run: |
          cd src
          npm run build

      - name: Deploy
        shell: sh
        env:
          MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
          MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
        run: |
          set -e
          npm -g install @platformos/pos-cli
          pos-cli deploy
          pos-cli constants set --name modules/openai/OPENAI_REINDEX_TOKEN --value ${{ secrets.OPENAI_REINDEX_TOKEN }}
          pos-cli constants set --name modules/openai/OPENAI_SECRET_TOKEN --value ${{ secrets.OPENAI_SECRET_TOKEN }}

      - name: Search reindex
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.MPKIT_PREVIEW_URL }}_embeddings/reindex.json'
          method: 'GET'
          data: '{"token": "${{ secrets.OPENAI_REINDEX_TOKEN }}"}'

      - name: Leave a comment after preview deployment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          recreate: true
          message: "\
            [PR Preview Action]\
            :---:

            :rocket: Deployed preview to ${{ secrets.MPKIT_PREVIEW_URL }}"
